/**
 * Preconstructed Commander deck definitions
 * Card names only - fetched from Scryfall on demand
 */

export const PRECON_DECKS = [
  // 5-COLOR: Najeela Warriors
  {
    id: 'najeela-warriors',
    name: 'Najeela, the Blade-Blossom',
    commander: 'Najeela, the Blade-Blossom',
    colors: ['W', 'U', 'B', 'R', 'G'],
    cards: [
      'Najeela, the Blade-Blossom',
      'Mindblade Render',
      'Tymna the Weaver',
      'Edric, Spymaster of Trest',
      'Bloodsoaked Champion',
      'Bramblewood Paragon',
      'Blood-Chin Rager',
      'Champion of Lambholt',
      'Chief of the Edge',
      'Chief of the Scale',
      'Combat Celebrant',
      'Druid of the Anima',
      'Embercleave',
      'Goblin Bushwhacker',
      'Grand Warlord Radha',
      'Herald of Secret Streams',
      'Jazal Goldmane',
      'Lovisa Coldeyes',
      'Mardu Woe-Reaper',
      'Mirror Entity',
      'Nature\'s Will',
      'Neheb, the Eternal',
      'Oakhame Adversary',
      'Ogre Battledriver',
      'Raiders\' Spoils',
      'Reckless Bushwhacker',
      'Rushblade Commander',
      'Samut, Voice of Dissent',
      'Secure the Wastes',
      'Shared Animosity',
      'Signal Pest',
      'Thrasher Brute',
      'Throne of the God-Pharaoh',
      'Zurgo Helmsmasher',
      'Derevi, Empyrial Tactician',
      'Druids\' Repository',
      'Bear Umbra',
      'Sword of Feast and Famine',
      'Aggravated Assault',
      'Aurelia, the Warleader',
      'Hellkite Charger',
      'Swords to Plowshares',
      'Path to Exile',
      'Cyclonic Rift',
      'Heroic Intervention',
      'Anguished Unmaking',
      'Kindred Discovery',
      'Reconnaissance',
      'Dolmen Gate',
      'Sol Ring',
      'Arcane Signet',
      'Chromatic Lantern',
      'Commander\'s Sphere',
      'Fellwar Stone',
      'Lightning Greaves',
      'Command Tower',
      'Mana Confluence',
      'City of Brass',
      'Exotic Orchard',
      'Reflecting Pool',
      'Cavern of Souls',
      'Unclaimed Territory',
      'Path of Ancestry',
      'Blood Crypt',
      'Breeding Pool',
      'Godless Shrine',
      'Hallowed Fountain',
      'Overgrown Tomb',
      'Sacred Foundry',
      'Steam Vents',
      'Stomping Ground',
      'Temple Garden',
      'Watery Grave',
      'Forest',
      'Island',
      'Mountain',
      'Plains',
      'Swamp',
      'Bloodstained Mire',
      'Flooded Strand',
      'Polluted Delta',
      'Windswept Heath',
      'Wooded Foothills',
      'Arid Mesa',
      'Marsh Flats',
      'Misty Rainforest',
      'Scalding Tarn',
      'Verdant Catacombs',
      'Boros Charm',
      'Naya Charm',
      'Abzan Charm',
      'Jeskai Charm',
      'Sultai Charm',
      'Brutal Hordechief',
      'Ankle Shanker',
      'Boldwyr Intimidator',
      'Obsidian Obelisk',
      'Talisman of Conviction',
      'Talisman of Creativity'
    ]
  },

  // 5-COLOR: Ur-Dragon
  {
    id: 'ur-dragon-dragons',
    name: 'The Ur-Dragon',
    commander: 'The Ur-Dragon',
    colors: ['W', 'U', 'B', 'R', 'G'],
    cards: [
      'The Ur-Dragon',
      'Dragonlord Ojutai',
      'Dragonlord Silumgar',
      'Dragonlord Kolaghan',
      'Dragonlord Atarka',
      'Dragonlord Dromoka',
      'Scion of the Ur-Dragon',
      'Niv-Mizzet, Parun',
      'Utvara Hellkite',
      'Scourge of Valkas',
      'Lathliss, Dragon Queen',
      'Terror of the Peaks',
      'Ancient Copper Dragon',
      'Ancient Gold Dragon',
      'Ancient Silver Dragon',
      'Old Gnawbone',
      'Savage Ventmaw',
      'Goldspan Dragon',
      'Glorybringer',
      'Thunderbreak Regent',
      'Dragon Tempest',
      'Temur Ascendancy',
      'Kindred Discovery',
      'Sarkhan Unbroken',
      'Sarkhan, Fireblood',
      'Patriarch\'s Bidding',
      'Living Death',
      'Crux of Fate',
      'Vanquisher\'s Banner',
      'Herald\'s Horn',
      'Urza\'s Incubator',
      'Dragon\'s Hoard',
      'Sol Ring',
      'Arcane Signet',
      'Chromatic Lantern',
      'Commander\'s Sphere',
      'Fist of Suns',
      'Morophon, the Boundless',
      'Command Tower',
      'Reflecting Pool',
      'Mana Confluence',
      'City of Brass',
      'Exotic Orchard',
      'Path of Ancestry',
      'Haven of the Spirit Dragon',
      'Unclaimed Territory',
      'Cavern of Souls',
      'Blood Crypt',
      'Breeding Pool',
      'Godless Shrine',
      'Hallowed Fountain',
      'Overgrown Tomb',
      'Sacred Foundry',
      'Steam Vents',
      'Stomping Ground',
      'Temple Garden',
      'Watery Grave',
      'Mountain',
      'Mountain',
      'Mountain',
      'Forest',
      'Forest',
      'Island',
      'Swamp',
      'Plains',
      'Drakuseth, Maw of Flames',
      'Balefire Dragon',
      'Hellkite Tyrant',
      'Steel Hellkite',
      'Klauth, Unrivaled Ancient',
      'Tiamat',
      'Dragon Broodmother',
      'Karrthus, Tyrant of Jund',
      'Atarka, World Render',
      'Silumgar, the Drifting Death',
      'Ojutai, Soul of Winter',
      'Dromoka, the Eternal',
      'Kolaghan, the Storm\'s Fury',
      'Spit Flame',
      'Decimate',
      'Rishkar\'s Expertise',
      'Kindred Charge',
      'Farseek',
      'Cultivate',
      'Kodama\'s Reach',
      'Nature\'s Lore',
      'Three Visits',
      'Skyshroud Claim',
      'Blasphemous Act',
      'Cyclonic Rift',
      'Swords to Plowshares',
      'Path to Exile',
      'Assassin\'s Trophy',
      'Beast Within',
      'Utter End',
      'Heroic Intervention',
      'Scalelord Reckoner',
      'Backdraft Hellkite'
    ]
  },

  // 4-COLOR: Atraxa Superfriends
  {
    id: 'atraxa-superfriends',
    name: 'Atraxa, Praetors\' Voice',
    commander: 'Atraxa, Praetors\' Voice',
    colors: ['W', 'U', 'B', 'G'],
    cards: [
      'Atraxa, Praetors\' Voice',
      'Deepglow Skate',
      'Evolution Sage',
      'Flux Channeler',
      'Fathom Mage',
      'Vorel of the Hull Clade',
      'Inexorable Tide',
      'Doubling Season',
      'Oath of Teferi',
      'The Chain Veil',
      'Jace, the Mind Sculptor',
      'Teferi, Hero of Dominaria',
      'Narset, Parter of Veils',
      'Liliana, Dreadhorde General',
      'Elspeth, Sun\'s Champion',
      'Tamiyo, Field Researcher',
      'Vraska, Relic Seeker',
      'Ugin, the Spirit Dragon',
      'Nissa, Who Shakes the World',
      'Karn Liberated',
      'Teferi, Time Raveler',
      'Jace, Wielder of Mysteries',
      'Ajani, Mentor of Heroes',
      'Swords to Plowshares',
      'Path to Exile',
      'Anguished Unmaking',
      'Assassin\'s Trophy',
      'Cyclonic Rift',
      'Wrath of God',
      'Damnation',
      'Supreme Verdict',
      'Sol Ring',
      'Arcane Signet',
      'Chromatic Lantern',
      'Coalition Relic',
      'Astral Cornucopia',
      'Everflowing Chalice',
      'Command Tower',
      'Breeding Pool',
      'Hallowed Fountain',
      'Watery Grave',
      'Godless Shrine',
      'Temple Garden',
      'Overgrown Tomb',
      'Flooded Strand',
      'Polluted Delta',
      'Windswept Heath',
      'Verdant Catacombs',
      'Misty Rainforest',
      'Yavimaya Coast',
      'Caves of Koilos',
      'Llanowar Wastes',
      'Underground River',
      'Exotic Orchard',
      'Mana Confluence',
      'City of Brass',
      'Reflecting Pool',
      'Forest',
      'Forest',
      'Plains',
      'Plains',
      'Island',
      'Island',
      'Swamp',
      'Swamp',
      'Interplanar Beacon',
      'Karn\'s Bastion',
      'Tamiyo, the Moon Sage',
      'Nissa, Vital Force',
      'Vraska, Golgari Queen',
      'Kiora, Behemoth Beckoner',
      'Ajani Steadfast',
      'Gideon Blackblade',
      'Vivien, Champion of the Wilds',
      'Spark Double',
      'Clever Impersonator',
      'Thrummingbird',
      'Grateful Apparition',
      'Contagion Engine',
      'Tezzeret\'s Gambit',
      'Oath of Nissa',
      'Pir, Imaginative Rascal',
      'Toothy, Imaginary Friend',
      'Kodama\'s Reach',
      'Cultivate',
      'Farseek',
      'Nature\'s Lore',
      'Rhystic Study',
      'Smothering Tithe',
      'Mirari\'s Wake',
      'Leyline of Anticipation',
      'Heroic Intervention',
      'Dovin\'s Veto',
      'Counterspell',
      'Swan Song',
      'Toxic Deluge',
      'Demonic Tutor'
    ]
  },

  // 3-COLOR: Isshin Attack Triggers
  {
    id: 'isshin-attack-triggers',
    name: 'Isshin, Two Heavens as One',
    commander: 'Isshin, Two Heavens as One',
    colors: ['R', 'W', 'B'],
    cards: [
      'Isshin, Two Heavens as One',
      'Adeline, Resplendent Cathar',
      'Hero of Bladehold',
      'Hanweir Garrison',
      'Aurelia, the Warleader',
      'Combat Celebrant',
      'Karlach, Fury of Avernus',
      'Raiyuu, Storm\'s Edge',
      'Delina, Wild Mage',
      'Krenko, Tin Street Kingpin',
      'Professional Face-Breaker',
      'Captain Lannery Storm',
      'Brutal Hordechief',
      'Mardu Strike Leader',
      'Alesha, Who Smiles at Death',
      'Fervent Charge',
      'Reconnaissance',
      'Duelist\'s Heritage',
      'Gratuitous Violence',
      'True Conviction',
      'Shared Animosity',
      'Goblin War Drums',
      'Dictate of Erebos',
      'Grave Pact',
      'Phyrexian Arena',
      'Swords to Plowshares',
      'Path to Exile',
      'Anguished Unmaking',
      'Crackling Doom',
      'Mortify',
      'Chaos Warp',
      'Terminate',
      'Wrath of God',
      'Damn',
      'Blasphemous Act',
      'Sol Ring',
      'Arcane Signet',
      'Boros Signet',
      'Orzhov Signet',
      'Rakdos Signet',
      'Talisman of Conviction',
      'Talisman of Hierarchy',
      'Talisman of Indulgence',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Command Tower',
      'Blood Crypt',
      'Godless Shrine',
      'Sacred Foundry',
      'Dragonskull Summit',
      'Isolated Chapel',
      'Clifftop Retreat',
      'Caves of Koilos',
      'Battlefield Forge',
      'Sulfurous Springs',
      'Savai Triome',
      'Nomad Outpost',
      'Path of Ancestry',
      'Vault of Champions',
      'Spectator Seating',
      'Luxury Suite',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Swamp',
      'Swamp',
      'Swamp',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Hellrider',
      'Breena, the Demagogue',
      'Emberwilde Captain',
      'Goldnight Commander',
      'Frontline Medic',
      'Tectonic Giant',
      'Port Razer',
      'Moraug, Fury of Akoum',
      'Anger',
      'Legion Loyalist',
      'Curse of Opulence',
      'Mirror Entity',
      'Dolmen Gate',
      'Iroas, God of Victory',
      'Cathars\' Crusade',
      'Fiery Emancipation',
      'Skullclamp',
      'Mask of Memory',
      'Sword of the Animist',
      'Berserkers\' Onslaught',
      'Agitator Ant',
      'Adriana, Captain of the Guard',
      'Karazikar, the Eye Tyrant',
      'Commissar Severina Raine'
    ]
  },

  // 2-COLOR: Elenda Vampires
  {
    id: 'elenda-vampires',
    name: 'Elenda, the Dusk Rose',
    commander: 'Elenda, the Dusk Rose',
    colors: ['W', 'B'],
    cards: [
      'Elenda, the Dusk Rose',
      'Blood Artist',
      'Bloodline Keeper',
      'Butcher of Malakir',
      'Champion of Dusk',
      'Cordial Vampire',
      'Dusk Legion Zealot',
      'Falkenrath Noble',
      'Indulgent Aristocrat',
      'Knight of the Ebon Legion',
      'Legion Lieutenant',
      'Malakir Bloodwitch',
      'Mavren Fein, Dusk Apostle',
      'Sanctum Seeker',
      'Twilight Prophet',
      'Vampire Nighthawk',
      'Viscera Seer',
      'Vito, Thorn of the Dusk Rose',
      'Yahenni, Undying Partisan',
      'Cruel Celebrant',
      'Anguished Unmaking',
      'Utter End',
      'Swords to Plowshares',
      'Path to Exile',
      'Mortify',
      'Vindicate',
      'Damn',
      'Wrath of God',
      'Toxic Deluge',
      'Living Death',
      'Phyrexian Arena',
      'Black Market',
      'Anointed Procession',
      'Dictate of Erebos',
      'Grave Pact',
      'Cathars\' Crusade',
      'Sol Ring',
      'Arcane Signet',
      'Orzhov Signet',
      'Talisman of Hierarchy',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Skullclamp',
      'Coat of Arms',
      'Door of Destinies',
      'Herald\'s Horn',
      'Vanquisher\'s Banner',
      'Command Tower',
      'Godless Shrine',
      'Isolated Chapel',
      'Caves of Koilos',
      'Concealed Courtyard',
      'Shambling Vent',
      'Vault of Champions',
      'Brightclimb Pathway',
      'Temple of Silence',
      'Orzhov Basilica',
      'Bojuka Bog',
      'Castle Locthwain',
      'Nykthos, Shrine to Nyx',
      'Urborg, Tomb of Yawgmoth',
      'Cabal Coffers',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Bloodghast',
      'Kalitas, Traitor of Ghet',
      'Patron of the Vein',
      'Captivating Vampire',
      'Edgar Markov',
      'Sorin, Imperious Bloodlord',
      'Read the Bones',
      'Sign in Blood',
      'Night\'s Whisper',
      'Austere Command',
      'Return to Dust',
      'Generous Gift',
      'New Blood',
      'Kindred Charge',
      'Forerunner of the Legion',
      'Bloodlord of Vaasgoth',
      'Stromkirk Captain',
      'Legion\'s Landing',
      'Oketra\'s Monument',
      'Bontu\'s Monument'
    ]
  },

  // MONO-WHITE: Giada Angels
  {
    id: 'giada-angels',
    name: 'Giada, Font of Hope',
    commander: 'Giada, Font of Hope',
    colors: ['W'],
    cards: [
      'Giada, Font of Hope',
      'Serra Ascendant',
      'Speaker of the Heavens',
      'Resplendent Angel',
      'Angel of Vitality',
      'Righteous Valkyrie',
      'Archangel of Thune',
      'Lyra Dawnbringer',
      'Angel of Destiny',
      'Shalai, Voice of Plenty',
      'Avacyn, Angel of Hope',
      'Linvala, Keeper of Silence',
      'Emeria Shepherd',
      'Angel of the Ruins',
      'Seraph of the Scales',
      'Bishop of Wings',
      'Angel of Jubilation',
      'Angelic Skirmisher',
      'Baneslayer Angel',
      'Serra the Benevolent',
      'Luminarch Ascension',
      'Divine Visitation',
      'Smothering Tithe',
      'Land Tax',
      'Swords to Plowshares',
      'Path to Exile',
      'Generous Gift',
      'Return to Dust',
      'Austere Command',
      'Wrath of God',
      'Day of Judgment',
      'Winds of Abandon',
      'Sol Ring',
      'Arcane Signet',
      'Pearl Medallion',
      'Herald\'s Horn',
      'Vanquisher\'s Banner',
      'Coat of Arms',
      'Door of Destinies',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Scroll of Avacyn',
      'Seraph Sanctuary',
      'Emeria, the Sky Ruin',
      'Nykthos, Shrine to Nyx',
      'Castle Ardenvale',
      'Eiganjo, Seat of the Empire',
      'War Room',
      'Myriad Landscape',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Starnheim Aspirant',
      'Youthful Valkyrie',
      'Firja\'s Retribution',
      'Sigarda\'s Splendor',
      'Inspiring Overseer',
      'Angelic Accord',
      'Well of Lost Dreams',
      'Alhammarret\'s Archive',
      'Endless Horizons',
      'Weathered Wayfarer',
      'Knight of the White Orchid',
      'Keeper of the Accord',
      'Esper Sentinel',
      'Enlightened Tutor',
      'Teferi\'s Protection',
      'Flawless Maneuver',
      'Resplendent Marshal',
      'Elesh Norn, Grand Cenobite',
      'Akroma, Vision of Ixidor',
      'Valkyrie Harbinger',
      'Emeria Angel',
      'Entreat the Angels'
    ]
  },

  // MONO-BLUE: Talrand Drakes
  {
    id: 'talrand-drakes',
    name: 'Talrand, Sky Summoner',
    commander: 'Talrand, Sky Summoner',
    colors: ['U'],
    cards: [
      'Talrand, Sky Summoner',
      'Baral, Chief of Compliance',
      'Snapcaster Mage',
      'Archaeomancer',
      'Murmuring Mystic',
      'Docent of Perfection',
      'Guile',
      'Torrential Gearhulk',
      'Consecrated Sphinx',
      'Jin-Gitaxias, Core Augur',
      'Counterspell',
      'Arcane Denial',
      'Negate',
      'Swan Song',
      'Pongify',
      'Rapid Hybridization',
      'Reality Shift',
      'Brainstorm',
      'Ponder',
      'Preordain',
      'Gitaxian Probe',
      'Opt',
      'Serum Visions',
      'Thought Scour',
      'Impulse',
      'Frantic Search',
      'Dig Through Time',
      'Treasure Cruise',
      'Cyclonic Rift',
      'Wash Away',
      'Force of Will',
      'Fierce Guardianship',
      'Mystic Confluence',
      'Rhystic Study',
      'Mystic Remora',
      'Ominous Seas',
      'Propaganda',
      'Sol Ring',
      'Arcane Signet',
      'Sapphire Medallion',
      'Sky Diamond',
      'Mind Stone',
      'Thought Vessel',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Sensei\'s Divining Top',
      'Reliquary Tower',
      'Mystic Sanctuary',
      'Castle Vantress',
      'Nykthos, Shrine to Nyx',
      'War Room',
      'Otawara, Soaring City',
      'Academy Ruins',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Shark Typhoon',
      'Mass Polymorph',
      'Blink of an Eye',
      'Into the Roil',
      'Vapor Snag',
      'Unsummon',
      'High Tide',
      'Time Warp',
      'Part the Waterveil',
      'Mana Drain',
      'Flusterstorm',
      'Mental Misstep',
      'Spell Pierce',
      'Delay',
      'Time Stop',
      'Commandeer',
      'Sublime Epiphany'
    ]
  },

  // MONO-BLACK: Yawgmoth Aristocrats
  {
    id: 'yawgmoth-aristocrats',
    name: 'Yawgmoth, Thran Physician',
    commander: 'Yawgmoth, Thran Physician',
    colors: ['B'],
    cards: [
      'Yawgmoth, Thran Physician',
      'Blood Artist',
      'Zulaport Cutthroat',
      'Cruel Celebrant',
      'Viscera Seer',
      'Carrion Feeder',
      'Reassembling Skeleton',
      'Bloodghast',
      'Nether Traitor',
      'Butcher Ghoul',
      'Geralf\'s Messenger',
      'Mikaeus, the Unhallowed',
      'Gray Merchant of Asphodel',
      'Kokusho, the Evening Star',
      'Sheoldred, Whispering One',
      'Grave Titan',
      'Sidisi, Undead Vizier',
      'Phyrexian Obliterator',
      'Plaguecrafter',
      'Fleshbag Marauder',
      'Endrek Sahr, Master Breeder',
      'Bitterblossom',
      'Phyrexian Arena',
      'Necropotence',
      'Black Market',
      'Grave Pact',
      'Dictate of Erebos',
      'Living Death',
      'Toxic Deluge',
      'Damnation',
      'Feed the Swarm',
      'Go for the Throat',
      'Deadly Rollick',
      'Vampiric Tutor',
      'Demonic Tutor',
      'Sol Ring',
      'Arcane Signet',
      'Jet Medallion',
      'Charcoal Diamond',
      'Mind Stone',
      'Thought Vessel',
      'Skullclamp',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Cabal Coffers',
      'Urborg, Tomb of Yawgmoth',
      'Nykthos, Shrine to Nyx',
      'Castle Locthwain',
      'Phyrexian Tower',
      'Volrath\'s Stronghold',
      'Bojuka Bog',
      'War Room',
      'Takenuma, Abandoned Mire',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Pawn of Ulamog',
      'Sifter of Skulls',
      'Pitiless Plunderer',
      'Ophiomancer',
      'Grim Haruspex',
      'Midnight Reaper',
      'Dark Prophecy',
      'Bastion of Remembrance',
      'Animate Dead',
      'Reanimate',
      'Exhume',
      'Entomb',
      'Buried Alive',
      'Dread Return',
      'Yawgmoth\'s Will',
      'K\'rrik, Son of Yawgmoth'
    ]
  },

  // MONO-RED: Krenko Goblins
  {
    id: 'krenko-goblins',
    name: 'Krenko, Mob Boss',
    commander: 'Krenko, Mob Boss',
    colors: ['R'],
    cards: [
      'Krenko, Mob Boss',
      'Goblin Chieftain',
      'Goblin King',
      'Goblin Warchief',
      'Goblin Ringleader',
      'Goblin Matron',
      'Goblin Recruiter',
      'Skirk Prospector',
      'Goblin Sledder',
      'Mogg War Marshal',
      'Goblin Instigator',
      'Legion Warboss',
      'Goblin Rabblemaster',
      'Muxus, Goblin Grandee',
      'Siege-Gang Commander',
      'Purphoros, God of the Forge',
      'Impact Tremors',
      'Goblin Bombardment',
      'Pashalik Mons',
      'Sling-Gang Lieutenant',
      'Goblin Trashmaster',
      'Goblin Sharpshooter',
      'Kiki-Jiki, Mirror Breaker',
      'Zealous Conscripts',
      'Lightning Bolt',
      'Chaos Warp',
      'Blasphemous Act',
      'Vandalblast',
      'Gamble',
      'Wheel of Fortune',
      'Reforge the Soul',
      'Jeska\'s Will',
      'Sol Ring',
      'Arcane Signet',
      'Ruby Medallion',
      'Fire Diamond',
      'Mind Stone',
      'Thought Vessel',
      'Herald\'s Horn',
      'Coat of Arms',
      'Door of Destinies',
      'Thornbite Staff',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Skullclamp',
      'Cavern of Souls',
      'Nykthos, Shrine to Nyx',
      'Castle Embereth',
      'War Room',
      'Sokenzan, Crucible of Defiance',
      'Myriad Landscape',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Goblin Piledriver',
      'Warren Instigator',
      'Goblin Lackey',
      'Conspicuous Snoop',
      'Rundvelt Hordemaster',
      'Hobgoblin Bandit Lord',
      'Battle Cry Goblin',
      'Goblin Chainwhirler',
      'Goblin Ruinblaster',
      'Tuktuk Scrapper',
      'Ogre Battledriver',
      'Shared Animosity',
      'Massive Raid',
      'Burn at the Stake',
      'Mob Justice',
      'Last-Ditch Effort'
    ]
  },

  // MONO-GREEN: Selvala Elves
  {
    id: 'selvala-elves',
    name: 'Selvala, Heart of the Wilds',
    commander: 'Selvala, Heart of the Wilds',
    colors: ['G'],
    cards: [
      'Selvala, Heart of the Wilds',
      'Llanowar Elves',
      'Elvish Mystic',
      'Fyndhorn Elves',
      'Arbor Elf',
      'Birds of Paradise',
      'Elvish Archdruid',
      'Priest of Titania',
      'Wirewood Channeler',
      'Marwyn, the Nurturer',
      'Circle of Dreams Druid',
      'Craterhoof Behemoth',
      'End-Raze Forerunners',
      'Finale of Devastation',
      'Natural Order',
      'Green Sun\'s Zenith',
      'Chord of Calling',
      'Beast Whisperer',
      'Glimpse of Nature',
      'Guardian Project',
      'Sylvan Library',
      'Concordant Crossroads',
      'Triumph of the Hordes',
      'Overwhelming Stampede',
      'Return of the Wildspeaker',
      'Heroic Intervention',
      'Veil of Summer',
      'Beast Within',
      'Krosan Grip',
      'Nature\'s Claim',
      'Sol Ring',
      'Arcane Signet',
      'Emerald Medallion',
      'Moss Diamond',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Skullclamp',
      'Staff of Domination',
      'Umbral Mantle',
      'Thousand-Year Elixir',
      'Growing Rites of Itlimoc',
      'Gaea\'s Cradle',
      'Nykthos, Shrine to Nyx',
      'Castle Garenbrig',
      'War Room',
      'Boseiju, Who Endures',
      'Wirewood Lodge',
      'Yavimaya Hollow',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Joraga Treespeaker',
      'Quirion Ranger',
      'Scryb Ranger',
      'Temur Sabertooth',
      'Eternal Witness',
      'Reclamation Sage',
      'Fierce Empath',
      'Regal Force',
      'Soul of the Harvest',
      'Primordial Sage',
      'Ezuri, Renegade Leader',
      'Imperious Perfect',
      'Elvish Champion',
      'Copperhorn Scout',
      'Timberwatch Elf',
      'Wellwisher',
      'Allosaurus Shepherd',
      'Collector Ouphe'
    ]
  }
];

/**
 * Get a precon deck by ID
 */
export function getPreconById(id) {
  return PRECON_DECKS.find(deck => deck.id === id) || null;
}

/**
 * Get all precon decks (for populating dropdown)
 */
export function getAllPrecons() {
  return PRECON_DECKS.map(({ id, name, commander, colors, cards }) => ({
    id,
    name,
    commander,
    colors,
    cardCount: cards.length
  }));
}
