/**
 * Preconstructed Commander deck definitions
 * Card names only - fetched from Scryfall on demand
 */

export const PRECON_DECKS = [
  // 5-COLOR: Najeela Warriors (Full deck with sideboard/maybeboard)
  {
    id: 'najeela-warriors',
    name: 'Najeela, the Blade-Blossom',
    commander: 'Najeela, the Blade-Blossom',
    colors: ['W', 'U', 'B', 'R', 'G'],
    cards: [
      'Najeela, the Blade-Blossom',
      'Mindblade Render',
      'Tymna the Weaver',
      'Edric, Spymaster of Trest',
      'Bloodsoaked Champion',
      'Bramblewood Paragon',
      'Blood-Chin Rager',
      'Champion of Lambholt',
      'Chief of the Edge',
      'Chief of the Scale',
      'Combat Celebrant',
      'Druid of the Anima',
      'Embercleave',
      'Goblin Bushwhacker',
      'Grand Warlord Radha',
      'Herald of Secret Streams',
      'Jazal Goldmane',
      'Lovisa Coldeyes',
      'Mardu Woe-Reaper',
      'Mirror Entity',
      'Nature\'s Will',
      'Neheb, the Eternal',
      'Oakhame Adversary',
      'Ogre Battledriver',
      'Raiders\' Spoils',
      'Reckless Bushwhacker',
      'Rushblade Commander',
      'Samut, Voice of Dissent',
      'Secure the Wastes',
      'Shared Animosity',
      'Signal Pest',
      'Thrasher Brute',
      'Throne of the God-Pharaoh',
      'Zurgo Helmsmasher',
      'Derevi, Empyrial Tactician',
      'Druids\' Repository',
      'Bear Umbra',
      'Sword of Feast and Famine',
      'Aggravated Assault',
      'Aurelia, the Warleader',
      'Hellkite Charger',
      'Swords to Plowshares',
      'Path to Exile',
      'Cyclonic Rift',
      'Heroic Intervention',
      'Anguished Unmaking',
      'Kindred Discovery',
      'Reconnaissance',
      'Dolmen Gate',
      'Sol Ring',
      'Arcane Signet',
      'Chromatic Lantern',
      'Commander\'s Sphere',
      'Fellwar Stone',
      'Lightning Greaves',
      'Command Tower',
      'Mana Confluence',
      'City of Brass',
      'Exotic Orchard',
      'Reflecting Pool',
      'Cavern of Souls',
      'Unclaimed Territory',
      'Path of Ancestry',
      'Blood Crypt',
      'Breeding Pool',
      'Godless Shrine',
      'Hallowed Fountain',
      'Overgrown Tomb',
      'Sacred Foundry',
      'Steam Vents',
      'Stomping Ground',
      'Temple Garden',
      'Watery Grave',
      'Forest',
      'Island',
      'Mountain',
      'Plains',
      'Swamp',
      'Bloodstained Mire',
      'Flooded Strand',
      'Polluted Delta',
      'Windswept Heath',
      'Wooded Foothills',
      'Arid Mesa',
      'Marsh Flats',
      'Misty Rainforest',
      'Scalding Tarn',
      'Verdant Catacombs',
      'Boros Charm',
      'Naya Charm',
      'Abzan Charm',
      'Jeskai Charm',
      'Sultai Charm',
      'Brutal Hordechief',
      'Ankle Shanker',
      'Boldwyr Intimidator',
      'Obsidian Obelisk',
      'Talisman of Conviction',
      'Talisman of Creativity'
    ],
    sideboard: [
      'Cathars\' Crusade',
      'Beastmaster Ascension',
      'Coat of Arms',
      'Vanquisher\'s Banner',
      'Herald\'s Horn',
      'Door of Destinies',
      'Grim Hireling',
      'Toski, Bearer of Secrets',
      'Skullclamp',
      'Swiftfoot Boots'
    ],
    maybeboard: [
      'Jetmir, Nexus of Revels',
      'Winota, Joiner of Forces',
      'Marisi, Breaker of the Coil',
      'Alesha, Who Smiles at Death',
      'Kari Zev, Skyship Raider',
      'Hanweir Garrison',
      'Legion Warboss',
      'Krenko, Tin Street Kingpin',
      'Adeline, Resplendent Cathar',
      'Hero of Bladehold'
    ]
  },

  // Duskmourn: Miracle Worker - Aminatou (Esper)
  {
    id: 'miracle-worker',
    name: 'Miracle Worker',
    commander: 'Aminatou, Veil Piercer',
    colors: ['W', 'U', 'B'],
    cards: [
      'Aminatou, Veil Piercer',
      'Archetype of Imagination',
      'Arvinox, the Mind Flail',
      'Athreos, Shroud-Veiled',
      'Auramancer',
      'Burnished Hart',
      'Demon of Fate\'s Design',
      'Doomwake Giant',
      'Dream Eater',
      'Nightmare Shepherd',
      'Mesa Enchantress',
      'Moon-Blessed Cleric',
      'Ondu Spiritdancer',
      'Prognostic Sphinx',
      'Solemn Simulacrum',
      'Starfield Mystic',
      'Verge Rangers',
      'Arcane Denial',
      'Brainstorm',
      'Inkshield',
      'Otherworldly Gaze',
      'Return to Dust',
      'Swords to Plowshares',
      'Thirst for Meaning',
      'Telling Time',
      'Utter End',
      'Aminatou\'s Augury',
      'Diabolic Vision',
      'Entreat the Angels',
      'Ponder',
      'Portent',
      'Read the Bones',
      'Terminus',
      'Time Wipe',
      'Cast Out',
      'Extravagant Replication',
      'Life Insurance',
      'Mirrormade',
      'Monologue Tax',
      'One with the Multiverse',
      'Shark Typhoon',
      'Sigil of the Empty Throne',
      'Sphere of Safety',
      'Spirit-Sister\'s Call',
      'The Eldest Reborn',
      'Timely Ward',
      'Arcane Signet',
      'Azorius Signet',
      'Brainstone',
      'Commander\'s Sphere',
      'Mind Stone',
      'Orzhov Signet',
      'Sol Ring',
      'Adarkar Wastes',
      'Arcane Sanctum',
      'Ash Barrens',
      'Azorius Chancery',
      'Bojuka Bog',
      'Caves of Koilos',
      'Dimir Aqueduct',
      'Evolving Wilds',
      'Halimar Depths',
      'Hall of Heliod\'s Generosity',
      'Obscura Storefront',
      'Orzhov Basilica',
      'Tainted Field',
      'Tainted Isle',
      'Temple of Deceit',
      'Temple of Enlightenment',
      'Temple of Silence',
      'Thriving Heath',
      'Thriving Isle',
      'Thriving Moor',
      'Underground River',
      'Command Tower',
      'Terramorphic Expanse',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Ancient Cellarspawn',
      'Metamorphosis Fanatic',
      'Phenomenon Investigators',
      'Redress Fate',
      'Soaring Lightbringer',
      'The Master of Keys'
    ],
    sideboard: [
      'Ghostly Prison',
      'Propaganda',
      'Blind Obedience',
      'Rhystic Study',
      'Smothering Tithe',
      'Necropotence',
      'Phyrexian Arena',
      'Esper Sentinel',
      'Austere Command',
      'Wrath of God'
    ],
    maybeboard: [
      'Teferi, Hero of Dominaria',
      'Narset, Parter of Veils',
      'Liliana, Dreadhorde General',
      'Kaya the Inexorable',
      'Elesh Norn, Grand Cenobite',
      'Sun Titan',
      'Grave Titan',
      'Consecrated Sphinx',
      'Cyclonic Rift',
      'Demonic Tutor'
    ]
  },

  // Duskmourn: Jump Scare! - Zimone (Simic)
  {
    id: 'jump-scare',
    name: 'Jump Scare!',
    commander: 'Zimone, Mystery Unraveler',
    colors: ['U', 'G'],
    cards: [
      'Zimone, Mystery Unraveler',
      'Aesi, Tyrant of Gyre Strait',
      'Arixmethes, Slumbering Isle',
      'Ashaya, Soul of the Wild',
      'Augur of Autumn',
      'Beanstalk Giant',
      'Body of Knowledge',
      'Citanul Hierophants',
      'Deathmist Raptor',
      'Greater Tanuki',
      'Hydra Omnivore',
      'Kefnet the Mindful',
      'Kheru Spellsnatcher',
      'Multani, Yavimaya\'s Avatar',
      'Rashmi, Eternities Crafter',
      'Sakura-Tribe Elder',
      'Scute Swarm',
      'Shigeki, Jukai Visionary',
      'Skaab Ruinator',
      'Tatyova, Benthic Druid',
      'Temur War Shaman',
      'Thunderfoot Baloth',
      'Trygon Predator',
      'Whisperwood Elemental',
      'Worldspine Wurm',
      'Yavimaya Elder',
      'Yedora, Grave Gardener',
      'Beast Within',
      'Biomass Mutation',
      'Cackling Counterpart',
      'Counterspell',
      'Dig Through Time',
      'Eureka Moment',
      'Growth Spiral',
      'Reality Shift',
      'Aether Gale',
      'Cultivate',
      'Explosive Vegetation',
      'Ezuri\'s Predation',
      'Oversimplify',
      'Overwhelming Stampede',
      'Rampant Growth',
      'Primordial Mist',
      'Retreat to Coralhelm',
      'Sandwurm Convergence',
      'Trail of Mystery',
      'Wilderness Reclamation',
      'Arcane Signet',
      'Scroll of Fate',
      'Simic Signet',
      'Sol Ring',
      'Ash Barrens',
      'Castle Vantress',
      'Command Tower',
      'Drownyard Temple',
      'Evolving Wilds',
      'Flooded Grove',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Hinterland Harbor',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Mosswort Bridge',
      'Myriad Landscape',
      'Overflowing Basin',
      'Quandrix Campus',
      'Reliquary Tower',
      'Simic Growth Chamber',
      'Tangled Islet',
      'Temple of Mystery',
      'Temple of the False God',
      'Terramorphic Expanse',
      'Thornwood Falls',
      'Vineglimmer Snarl',
      'Yavimaya Coast',
      'Curator Beastie',
      'Disorienting Choice',
      'Giggling Skitterspike',
      'Glitch Interpreter',
      'Growing Dread',
      'Overgrown Zealot',
      'Shriekwood Devourer',
      'Zimone\'s Hypothesis'
    ],
    sideboard: [
      'Cyclonic Rift',
      'Kodama of the East Tree',
      'Avenger of Zendikar',
      'Craterhoof Behemoth',
      'Tireless Tracker',
      'Oracle of Mul Daya',
      'Mystic Remora',
      'Rhystic Study',
      'Burgeoning',
      'Exploration'
    ],
    maybeboard: [
      'Uro, Titan of Nature\'s Wrath',
      'Prime Speaker Zegana',
      'Koma, Cosmos Serpent',
      'Vorinclex, Monstrous Raider',
      'Finale of Devastation',
      'Green Sun\'s Zenith',
      'Chord of Calling',
      'Alchemist\'s Refuge',
      'Breeding Pool',
      'Misty Rainforest'
    ]
  },

  // Duskmourn: Endless Punishment - Valgavoth (Rakdos)
  {
    id: 'endless-punishment',
    name: 'Endless Punishment',
    commander: 'Valgavoth, Harrower of Souls',
    colors: ['B', 'R'],
    cards: [
      'Valgavoth, Harrower of Souls',
      'Blood Artist',
      'Blood Seeker',
      'Braids, Arisen Nightmare',
      'Brash Taunter',
      'Combustible Gearhulk',
      'Falkenrath Noble',
      'Fate Unraveler',
      'Florian, Voldaren Scion',
      'Gray Merchant of Asphodel',
      'Harsh Mentor',
      'Kaervek the Merciless',
      'Kardur, Doomscourge',
      'Kederekt Parasite',
      'Massacre Girl',
      'Massacre Wurm',
      'Mayhem Devil',
      'Mogis, God of Slaughter',
      'Morbid Opportunist',
      'Nightshade Harvester',
      'Rakdos, Lord of Riots',
      'Rampaging Ferocidon',
      'Solemn Simulacrum',
      'Stormfist Crusader',
      'Syr Konrad, the Grim',
      'Tectonic Giant',
      'The Lord of Pain',
      'Vial Smasher the Fierce',
      'Barbflare Gremlin',
      'Gleeful Arsonist',
      'Persistent Constrictor',
      'Star Athlete',
      'Blasphemous Act',
      'Decree of Pain',
      'Feed the Swarm',
      'Light Up the Stage',
      'Sign in Blood',
      'Bedevil',
      'Blood Pact',
      'Chaos Warp',
      'Infernal Grasp',
      'Rakdos Charm',
      'Bastion of Remembrance',
      'Spiteful Visions',
      'Theater of Horrors',
      'Enchanter\'s Bane',
      'Arcane Signet',
      'Basilisk Collar',
      'Fellwar Stone',
      'Lightning Greaves',
      'Mask of Griselbrand',
      'Mind Stone',
      'Rakdos Signet',
      'Sol Ring',
      'Talisman of Indulgence',
      'Thought Vessel',
      'Ash Barrens',
      'Blackcleave Cliffs',
      'Bloodfell Caves',
      'Canyon Slough',
      'Command Tower',
      'Dragonskull Summit',
      'Evolving Wilds',
      'Exotic Orchard',
      'Foreboding Ruins',
      'Geothermal Bog',
      'Graven Cairns',
      'Leechridden Swamp',
      'Shadowblood Ridge',
      'Shivan Gorge',
      'Smoldering Marsh',
      'Spinerock Knoll',
      'Sulfurous Springs',
      'Tainted Peak',
      'Temple of Malice',
      'Temple of the False God',
      'Terramorphic Expanse',
      'Witch\'s Clinic',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Fear of Burning Alive',
      'Grab the Prize',
      'Sadistic Shell Game',
      'Suspended Sentence'
    ],
    sideboard: [
      'Sheoldred, the Apocalypse',
      'Dockside Extortionist',
      'Archfiend of Despair',
      'Wound Reflection',
      'Torbran, Thane of Red Fell',
      'Neheb, the Eternal',
      'Exquisite Blood',
      'Bloodchief Ascension',
      'K\'rrik, Son of Yawgmoth',
      'Toxic Deluge'
    ],
    maybeboard: [
      'Kroxa, Titan of Death\'s Hunger',
      'Ob Nixilis, the Adversary',
      'Chainer, Nightmare Adept',
      'Rakdos, the Showstopper',
      'Strefan, Maurer Progenitor',
      'Olivia Voldaren',
      'Captive Audience',
      'Fraying Omnipotence',
      'Blood Crypt',
      'Luxury Suite'
    ]
  },

  // Duskmourn: Death Toll - Winter (Golgari)
  {
    id: 'death-toll',
    name: 'Death Toll',
    commander: 'Winter, Cynical Opportunist',
    colors: ['B', 'G'],
    cards: [
      'Winter, Cynical Opportunist',
      'Burnished Hart',
      'Carrion Grub',
      'Deathcap Cultivator',
      'Dryad Arbor',
      'Giant Adephage',
      'Gnarlwood Dryad',
      'Grim Flayer',
      'Haywire Mite',
      'Hornet Queen',
      'Ishkanah, Grafwidow',
      'Moldgraf Millipede',
      'Moldgraf Monstrosity',
      'Noxious Gearhulk',
      'Nyx Weaver',
      'Obsessive Skinner',
      'Old Stickfingers',
      'Sakura-Tribe Elder',
      'Scavenging Ooze',
      'Skola Grovedancer',
      'Solemn Simulacrum',
      'Stitcher\'s Supplier',
      'Titania, Nature\'s Force',
      'Demolisher Spawn',
      'Rendmaw, Creaking Nest',
      'Ursine Monstrosity',
      'Vile Mutilator',
      'Culling Ritual',
      'Formless Genesis',
      'Harmonize',
      'Mulch',
      'Night\'s Whisper',
      'Rampant Growth',
      'Reanimate',
      'Convert to Slime',
      'Deluge of Doom',
      'Arachnogenesis',
      'Grapple with the Past',
      'Grisly Salvage',
      'Harrow',
      'Inscription of Abundance',
      'Putrefy',
      'Binding the Old Gods',
      'Cemetery Tampering',
      'Crawling Sensation',
      'Deadbridge Chant',
      'Deathreap Ritual',
      'Whip of Erebos',
      'Grist, the Hunger Tide',
      'Ob Nixilis Reignited',
      'Professor Onyx',
      'Wrenn and Seven',
      'Arcane Signet',
      'Commander\'s Sphere',
      'Golgari Signet',
      'Mind Stone',
      'Sol Ring',
      'Talisman of Resilience',
      'Ash Barrens',
      'Barren Moor',
      'Bojuka Bog',
      'Command Tower',
      'Darkmoss Bridge',
      'Evolving Wilds',
      'Exotic Orchard',
      'Golgari Rot Farm',
      'Grim Backwoods',
      'Jungle Hollow',
      'Llanowar Wastes',
      'Necroblossom Snarl',
      'Reliquary Tower',
      'Tainted Wood',
      'Temple of Malady',
      'Temple of the False God',
      'Terramorphic Expanse',
      'Tranquil Thicket',
      'Twilight Mire',
      'Viridescent Bog',
      'Woodland Cemetery',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Demonic Covenant',
      'Into the Pit',
      'Suspicious Bookcase'
    ],
    sideboard: [
      'Meren of Clan Nel Toth',
      'Jarad, Golgari Lich Lord',
      'Eternal Witness',
      'Hogaak, Arisen Necropolis',
      'Lord of Extinction',
      'Massacre Wurm',
      'Living Death',
      'Bane of Progress',
      'Sylvan Library',
      'Dictate of Erebos'
    ],
    maybeboard: [
      'The Gitrog Monster',
      'Titania, Protector of Argoth',
      'Sheoldred, Whispering One',
      'Craterhoof Behemoth',
      'Splinterfright',
      'Life from the Loam',
      'Assassin\'s Trophy',
      'Abrupt Decay',
      'Overgrown Tomb',
      'Verdant Catacombs'
    ]
  },

  // Bloomburrow: Animated Army - Bello (Gruul)
  {
    id: 'animated-army',
    name: 'Animated Army',
    commander: 'Bello, Bard of the Brambles',
    colors: ['R', 'G'],
    cards: [
      'Bello, Bard of the Brambles',
      'Domri, Anarch of Bolas',
      'Burnished Hart',
      'Etali, Primal Storm',
      'Garruk\'s Packleader',
      'Ghalta, Primal Hunger',
      'Goreclaw, Terror of Qal Sisma',
      'Grothama, All-Devouring',
      'Grumgully, the Generous',
      'Kodama of the East Tree',
      'Llanowar Loamspeaker',
      'Lotus Cobra',
      'Rampaging Baloths',
      'Sakura-Tribe Elder',
      'Tendershoot Dryad',
      'Abrade',
      'Beast Within',
      'Big Score',
      'Chaos Warp',
      'Starstorm',
      'Blasphemous Act',
      'Cultivate',
      'Decimate',
      'Explore',
      'Farseek',
      'Harmonize',
      'Rampant Growth',
      'Berserkers\' Onslaught',
      'Garruk\'s Uprising',
      'Gratuitous Violence',
      'Greater Good',
      'Outpost Siege',
      'Path of Discovery',
      'Primeval Bounty',
      'Rain of Riches',
      'Sunbird\'s Invocation',
      'Unnatural Growth',
      'Warstorm Surge',
      'Arcane Signet',
      'Bootleggers\' Stash',
      'Esika\'s Chariot',
      'Fellwar Stone',
      'Gilded Lotus',
      'Gruul Signet',
      'Hedron Archive',
      'Mind Stone',
      'Sol Ring',
      'Spine of Ish Sah',
      'Talisman of Impulse',
      'Thought Vessel',
      'Thran Dynamo',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Cinder Glade',
      'Command Tower',
      'Copperline Gorge',
      'Evolving Wilds',
      'Exotic Orchard',
      'Forgotten Cave',
      'Game Trail',
      'Gruul Turf',
      'Karplusan Forest',
      'Mossfire Valley',
      'Mosswort Bridge',
      'Path of Ancestry',
      'Raging Ravine',
      'Reliquary Tower',
      'Rootbound Crag',
      'Sheltered Thicket',
      'Temple of Abandon',
      'Terramorphic Expanse',
      'Tranquil Thicket',
      'Wooded Ridgeline',
      'Alchemist\'s Talent',
      'Brightcap Badger',
      'Evercoat Ursine',
      'Prosperous Bandit',
      'Pyreswipe Hawk',
      'Rolling Hamsphere',
      'Teapot Slinger',
      'Thickest in the Thicket',
      'Trailtracker Scout',
      'Wandertale Mentor',
      'Wildsear, Scouring Maw'
    ],
    sideboard: [
      'Xenagos, God of Revels',
      'Vorinclex, Voice of Hunger',
      'Siege Behemoth',
      'Pathbreaker Ibex',
      'Aggravated Assault',
      'Parallel Lives',
      'Doubling Season',
      'Finale of Devastation',
      'Heroic Intervention',
      'Worldly Tutor'
    ],
    maybeboard: [
      'Maelstrom Wanderer',
      'Ruric Thar, the Unbowed',
      'Samut, Voice of Dissent',
      'Ilharg, the Raze-Boar',
      'Terror of the Peaks',
      'Balefire Dragon',
      'Inferno Titan',
      'Ravager Wurm',
      'Stomping Ground',
      'Wooded Foothills'
    ]
  },

  // Final Fantasy: Limit Break - Cloud (Naya)
  {
    id: 'limit-break',
    name: 'Limit Break',
    commander: 'Cloud, Ex-SOLDIER',
    colors: ['R', 'G', 'W'],
    cards: [
      'Cloud, Ex-SOLDIER',
      'Aerith, Last Ancient',
      'Armory Automaton',
      'Barret Wallace',
      'Bastion Protector',
      'Bronze Guardian',
      'Bugenhagen, Wise Elder',
      'Cait Sith, Fortune Teller',
      'Cid, Freeflier Pilot',
      'Elena, Turk Recruit',
      'Heidegger, Shinra Executive',
      'Helitrooper',
      'Hellkite Tyrant',
      'Professional Face-Breaker',
      'Professor Hojo',
      'Puresteel Paladin',
      'Red XIII, Proud Warrior',
      'Sephiroth, Fallen Hero',
      'Tifa, Martial Artist',
      'Vincent, Vengeful Atoner',
      'Yuffie, Materia Hunter',
      'Zack Fair',
      'Chaos Warp',
      'Clever Concealment',
      'Dispatch',
      'Austere Command',
      'Cultivate',
      'Decimate',
      'Harmonize',
      'Nature\'s Lore',
      'Rampant Growth',
      'Secret Rendezvous',
      'Unfinished Business',
      'Vandalblast',
      'Vanquish the Horde',
      'Furious Rise',
      'Arcane Signet',
      'Behemoth Sledge',
      'Champion\'s Helm',
      'Colossus Hammer',
      'Conqueror\'s Flail',
      'Darksteel Plate',
      'Explorer\'s Scope',
      'Hero\'s Blade',
      'Inspiring Statuary',
      'Lightning Greaves',
      'Mask of Memory',
      'Skullclamp',
      'Sol Ring',
      'Sword of the Animist',
      'Trailblazer\'s Boots',
      'Ash Barrens',
      'Battlefield Forge',
      'Bonders\' Enclave',
      'Brushland',
      'Canopy Vista',
      'Cinder Glade',
      'Clifftop Retreat',
      'Command Tower',
      'Evolving Wilds',
      'Exotic Orchard',
      'Fire-Lit Thicket',
      'Fortified Village',
      'Furycalm Snarl',
      'Game Trail',
      'Jungle Shrine',
      'Mossfire Valley',
      'Path of Ancestry',
      'Rootbound Crag',
      'Rugged Prairie',
      'Scavenger Grounds',
      'Slayers\' Stronghold',
      'Spire of Industry',
      'Sungrass Prairie',
      'Sunpetal Grove',
      'Forest',
      'Forest',
      'Forest',
      'Mountain',
      'Mountain',
      'Mountain',
      'Plains',
      'Plains',
      'Plains',
      'Lifestream\'s Blessing',
      'Cloud\'s Limit Break',
      'Ultimate Magic Holy',
      'Ultimate Magic Meteor',
      'SOLDIER Military Program',
      'Summoning Materia',
      'Hero\'s Heirloom',
      'Wrecking Ball Arm',
      'Conformer Shuriken',
      'Avalanche of Sector 7',
      'Barret, Avalanche Leader',
      'Summon Kujata'
    ],
    sideboard: [
      'Godo, Bandit Warlord',
      'Nazahn, Revered Bladesmith',
      'Kemba, Kha Regent',
      'Aurelia, the Warleader',
      'Stonehewer Giant',
      'Stoneforge Mystic',
      'Sigarda\'s Aid',
      'Open the Armory',
      'Hammer of Nazahn',
      'Sword of Feast and Famine'
    ],
    maybeboard: [
      'Akiri, Fearless Voyager',
      'Ardenn, Intrepid Archaeologist',
      'Halvar, God of Battle',
      'Blade Historian',
      'Embercleave',
      'Shadowspear',
      'Umezawa\'s Jitte',
      'Steelshaper\'s Gift',
      'Sacred Foundry',
      'Windswept Heath'
    ]
  },

  // Final Fantasy: Counter Blitz - Tidus (Bant)
  {
    id: 'counter-blitz',
    name: 'Counter Blitz',
    commander: 'Tidus, Yuna\'s Guardian',
    colors: ['W', 'U', 'G'],
    cards: [
      'Tidus, Yuna\'s Guardian',
      'Altered Ego',
      'Auron, Venerated Guardian',
      'Bane of Progress',
      'Chasm Skulker',
      'Duskshell Crawler',
      'Fathom Mage',
      'Forgotten Ancient',
      'Generous Patron',
      'Grateful Apparition',
      'Gyre Sage',
      'Incubation Druid',
      'Kimahri, Valiant Guardian',
      'Lord Jyscal Guado',
      'Lulu, Stern Guardian',
      'Luminous Broodmoth',
      'Maester Seymour',
      'O\'aka, Traveling Merchant',
      'Rampant Rejuvenator',
      'Rikku, Resourceful Guardian',
      'Scholar of New Horizons',
      'Shelinda, Yevon Acolyte',
      'Sin, Unending Cataclysm',
      'Sunscorch Regent',
      'Tireless Tracker',
      'Tromell, Seymour\'s Butler',
      'Wakka, Devoted Guardian',
      'Walking Ballista',
      'Yuna, Grand Summoner',
      'Chocobo Knights',
      'Gatta and Luzzu',
      'Summon Ixion',
      'Summon Magus Sisters',
      'Summon Valefor',
      'Summon Yojimbo',
      'An Offer You Can\'t Refuse',
      'Destroy Evil',
      'Endless Detour',
      'Inspiring Call',
      'Path to Exile',
      'Pull from Tomorrow',
      'Collective Effort',
      'Damning Verdict',
      'Farewell',
      'Farseek',
      'Promise of Loyalty',
      'Three Visits',
      'Bred for the Hunt',
      'Fight Rigging',
      'Hardened Scales',
      'Inexorable Tide',
      'Path of Discovery',
      'Resourceful Defense',
      'Together Forever',
      'Arcane Signet',
      'Everflowing Chalice',
      'Sol Ring',
      'Ash Barrens',
      'Brushland',
      'Canopy Vista',
      'Command Tower',
      'Evolving Wilds',
      'Exotic Orchard',
      'Flooded Grove',
      'Forge of Heroes',
      'Fortified Village',
      'Glacial Fortress',
      'Hinterland Harbor',
      'Nesting Grounds',
      'Overflowing Basin',
      'Path of Ancestry',
      'Port Town',
      'Prairie Stream',
      'Seaside Citadel',
      'Skycloud Expanse',
      'Sungrass Prairie',
      'Sunpetal Grove',
      'Tangled Islet',
      'Temple of Enlightenment',
      'Temple of Mystery',
      'Temple of Plenty',
      'Temple of the False God',
      'Vineglimmer Snarl',
      'Forest',
      'Forest',
      'Forest',
      'Island',
      'Island',
      'Island',
      'Plains',
      'Plains',
      'Plains',
      'Protection Magic',
      'Yuna\'s Whistle',
      'Yuna\'s Decision',
      'Sphere Grid',
      'Summoner\'s Sending',
      'Blitzball Stadium',
      'Idyllic Beachfront',
      'Radiant Grove'
    ],
    sideboard: [
      'Atraxa, Praetors\' Voice',
      'Vorel of the Hull Clade',
      'Doubling Season',
      'The Ozolith',
      'Branching Evolution',
      'Teferi\'s Protection',
      'Cyclonic Rift',
      'Swords to Plowshares',
      'Simic Ascendancy',
      'Deepglow Skate'
    ],
    maybeboard: [
      'Pir, Imaginative Rascal',
      'Toothy, Imaginary Friend',
      'Gilder Bairn',
      'Kalonian Hydra',
      'Managorger Hydra',
      'Herald of Secret Streams',
      'Flux Channeler',
      'Evolution Sage',
      'Breeding Pool',
      'Hallowed Fountain'
    ]
  },

  // Final Fantasy: Revival Trance - Terra (Mardu)
  {
    id: 'revival-trance',
    name: 'Revival Trance',
    commander: 'Terra, Herald of Hope',
    colors: ['W', 'B', 'R'],
    cards: [
      'Terra, Herald of Hope',
      'Angel of the Ruins',
      'Anger',
      'Archfiend of Depravity',
      'Banon, the Returners\' Leader',
      'Celes, Rune Knight',
      'Combustible Gearhulk',
      'Cyan, Vengeful Samurai',
      'Edgar, Master Machinist',
      'Flayer of the Hatebound',
      'Gau, Feral Youth',
      'General Leo Cristophe',
      'Gogo, Mysterious Mime',
      'Interceptor, Shadow\'s Hound',
      'Kefka, Dancing Mad',
      'Locke, Treasure Hunter',
      'Meteor Golem',
      'Millikin',
      'Mog, Moogle Warrior',
      'Morbid Opportunist',
      'Palace Jailer',
      'Pitiless Plunderer',
      'Priest of Fell Rites',
      'Ruin Grinder',
      'Sabin, Master Monk',
      'Sepulchral Primordial',
      'Setzer, Wandering Gambler',
      'Shadow, Mysterious Assassin',
      'Siegfried, Famed Swordsman',
      'Solemn Simulacrum',
      'Stitcher\'s Supplier',
      'Strago and Relm',
      'Sun Titan',
      'The Warring Triad',
      'Umaro, Raging Yeti',
      'Bedevil',
      'Big Score',
      'Crackling Doom',
      'Espers to Magicite',
      'Laughing Mad',
      'Mortify',
      'Legions to Ashes',
      'Night\'s Whisper',
      'Reanimate',
      'Rejoin the Fight',
      'Rise of the Dark Realms',
      'Ruinous Ultimatum',
      'Snort',
      'Stitch Together',
      'Tragic Arrogance',
      'Arcane Signet',
      'Coin of Fate',
      'Commander\'s Sphere',
      'Key to the City',
      'Mind Stone',
      'Phoenix Down',
      'Sol Ring',
      'Swiftfoot Boots',
      'Talisman of Conviction',
      'Talisman of Indulgence',
      'Wayfarer\'s Bauble',
      'Ash Barrens',
      'Battlefield Forge',
      'Clifftop Retreat',
      'Command Tower',
      'Demolition Field',
      'Desolate Mire',
      'Dragonskull Summit',
      'Evolving Wilds',
      'Exotic Orchard',
      'Fetid Heath',
      'Foreboding Ruins',
      'Furycalm Snarl',
      'Geothermal Bog',
      'Graven Cairns',
      'High Market',
      'Isolated Chapel',
      'Nomad Outpost',
      'Path of Ancestry',
      'Rogue\'s Passage',
      'Rugged Prairie',
      'Shadowblood Ridge',
      'Shineshadow Snarl',
      'Smoldering Marsh',
      'Sulfurous Springs',
      'Sunlit Marsh',
      'Mountain',
      'Mountain',
      'Mountain',
      'Swamp',
      'Swamp',
      'Swamp',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Summon Esper Valigarmanda',
      'The Falcon, Airship Restored'
    ],
    sideboard: [
      'Kaalia of the Vast',
      'Alesha, Who Smiles at Death',
      'Isshin, Two Heavens as One',
      'Living Death',
      'Animate Dead',
      'Phyrexian Arena',
      'Dictate of Erebos',
      'Grave Pact',
      'Smothering Tithe',
      'Toxic Deluge'
    ],
    maybeboard: [
      'Liesa, Shroud of Dusk',
      'Tariel, Reckoner of Souls',
      'Ravos, Soultender',
      'Elenda, the Dusk Rose',
      'Karmic Guide',
      'Reveillark',
      'Entomb',
      'Buried Alive',
      'Blood Crypt',
      'Godless Shrine'
    ]
  },

  // INCOMPLETE: Mono-White Angels (50 cards - Work in Progress)
  {
    id: 'angels-incomplete',
    name: 'Angelic Host (Incomplete)',
    commander: 'Giada, Font of Hope',
    colors: ['W'],
    cards: [
      'Giada, Font of Hope',
      'Serra Ascendant',
      'Speaker of the Heavens',
      'Resplendent Angel',
      'Angel of Vitality',
      'Righteous Valkyrie',
      'Archangel of Thune',
      'Lyra Dawnbringer',
      'Angel of Destiny',
      'Shalai, Voice of Plenty',
      'Linvala, Keeper of Silence',
      'Emeria Shepherd',
      'Bishop of Wings',
      'Angel of Jubilation',
      'Angelic Skirmisher',
      'Baneslayer Angel',
      'Luminarch Ascension',
      'Divine Visitation',
      'Swords to Plowshares',
      'Path to Exile',
      'Generous Gift',
      'Return to Dust',
      'Wrath of God',
      'Sol Ring',
      'Arcane Signet',
      'Pearl Medallion',
      'Herald\'s Horn',
      'Vanquisher\'s Banner',
      'Lightning Greaves',
      'Seraph Sanctuary',
      'Emeria, the Sky Ruin',
      'Nykthos, Shrine to Nyx',
      'Castle Ardenvale',
      'Command Tower',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains'
    ],
    sideboard: [],
    maybeboard: []
  }
];

/**
 * Get a precon deck by ID
 */
export function getPreconById(id) {
  return PRECON_DECKS.find(deck => deck.id === id) || null;
}

/**
 * Get all precon decks (for populating dropdown)
 */
export function getAllPrecons() {
  return PRECON_DECKS.map(({ id, name, commander, colors, cards, sideboard = [], maybeboard = [] }) => ({
    id,
    name,
    commander,
    colors,
    cardCount: cards.length,
    sideboardCount: sideboard.length,
    maybeboardCount: maybeboard.length
  }));
}
