/**
 * Preconstructed Commander deck definitions
 * Card names only - fetched from Scryfall on demand
 */

export const PRECON_DECKS = [
  {
    id: 'elenda-vampires',
    name: 'Elenda, the Dusk Rose',
    commander: 'Elenda, the Dusk Rose',
    colors: ['W', 'B'],
    cards: [
      'Elenda, the Dusk Rose',
      'Blood Artist',
      'Bloodline Keeper',
      'Butcher of Malakir',
      'Champion of Dusk',
      'Cordial Vampire',
      'Dusk Legion Zealot',
      'Falkenrath Noble',
      'Indulgent Aristocrat',
      'Knight of the Ebon Legion',
      'Legion Lieutenant',
      'Malakir Bloodwitch',
      'Mavren Fein, Dusk Apostle',
      'Sanctum Seeker',
      'Twilight Prophet',
      'Vampire Nighthawk',
      'Viscera Seer',
      'Vito, Thorn of the Dusk Rose',
      'Yahenni, Undying Partisan',
      'Zagras, Thief of Heartbeats',
      'Anguished Unmaking',
      'Utter End',
      'Swords to Plowshares',
      'Path to Exile',
      'Mortify',
      'Vindicate',
      'Damn',
      'Wrath of God',
      'Toxic Deluge',
      'Living Death',
      'Phyrexian Arena',
      'Black Market',
      'Anointed Procession',
      'Dictate of Erebos',
      'Grave Pact',
      'Cathars Crusade',
      'Sol Ring',
      'Arcane Signet',
      'Orzhov Signet',
      'Talisman of Hierarchy',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Skullclamp',
      'Coat of Arms',
      'Door of Destinies',
      'Herald\'s Horn',
      'Vanquisher\'s Banner',
      'Command Tower',
      'Godless Shrine',
      'Isolated Chapel',
      'Caves of Koilos',
      'Concealed Courtyard',
      'Shambling Vent',
      'Vault of Champions',
      'Brightclimb Pathway',
      'Temple of Silence',
      'Orzhov Basilica',
      'Tainted Field',
      'Bojuka Bog',
      'Castle Locthwain',
      'Nykthos, Shrine to Nyx',
      'Urborg, Tomb of Yawgmoth',
      'Cabal Coffers',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Cruel Celebrant',
      'Bloodghast',
      'Kalitas, Traitor of Ghet',
      'Patron of the Vein',
      'Bloodlord of Vaasgoth',
      'Captivating Vampire',
      'Stromkirk Captain',
      'Forerunner of the Legion',
      'New Blood',
      'Kindred Charge',
      'Kindred Dominance',
      'Edgar Markov',
      'Sorin, Imperious Bloodlord',
      'Read the Bones',
      'Sign in Blood',
      'Night\'s Whisper',
      'Painful Truths',
      'Austere Command',
      'Return to Dust',
      'Generous Gift'
    ]
  },
  {
    id: 'wilhelt-zombies',
    name: 'Wilhelt, the Rotcleaver',
    commander: 'Wilhelt, the Rotcleaver',
    colors: ['U', 'B'],
    cards: [
      'Wilhelt, the Rotcleaver',
      'Gravecrawler',
      'Cryptbreaker',
      'Carrion Feeder',
      'Diregraf Ghoul',
      'Undead Augur',
      'Plague Belcher',
      'Death Baron',
      'Lord of the Undead',
      'Cemetery Reaper',
      'Diregraf Colossus',
      'Undead Warchief',
      'Diregraf Captain',
      'Gleaming Overseer',
      'Noxious Ghoul',
      'Gray Merchant of Asphodel',
      'Sidisi, Undead Vizier',
      'Mikaeus, the Unhallowed',
      'Grave Titan',
      'Gisa and Geralf',
      'Grimgrin, Corpse-Born',
      'The Scarab God',
      'Rooftop Storm',
      'Endless Ranks of the Dead',
      'Liliana\'s Mastery',
      'Open the Graves',
      'Graf Harvest',
      'Necromancer\'s Stockpile',
      'Phyrexian Arena',
      'Rhystic Study',
      'Ponder',
      'Preordain',
      'Brainstorm',
      'Counterspell',
      'Negate',
      'Cyclonic Rift',
      'Damnation',
      'Toxic Deluge',
      'Feed the Swarm',
      'Go for the Throat',
      'Sol Ring',
      'Arcane Signet',
      'Dimir Signet',
      'Talisman of Dominance',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Coat of Arms',
      'Door of Destinies',
      'Herald\'s Horn',
      'Command Tower',
      'Watery Grave',
      'Drowned Catacomb',
      'Underground River',
      'Darkslick Shores',
      'Clearwater Pathway',
      'Temple of Deceit',
      'Dimir Aqueduct',
      'Tainted Isle',
      'Bojuka Bog',
      'Castle Locthwain',
      'Unholy Grotto',
      'Cavern of Souls',
      'Urborg, Tomb of Yawgmoth',
      'Cabal Coffers',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Army of the Damned',
      'Dark Salvation',
      'From Under the Floorboards',
      'Dread Summons',
      'Living Death',
      'Patriarch\'s Bidding',
      'Zombie Apocalypse',
      'Empty the Pits',
      'Liliana, Untouched by Death',
      'Liliana, Dreadhorde General',
      'Ghoulcaller Gisa',
      'Acererak the Archlich',
      'Champion of the Perished',
      'Headless Rider',
      'Poppet Stitcher',
      'Death Tyrant',
      'Rot Hulk',
      'Ebondeath, Dracolich',
      'Bladewing the Risen'
    ]
  },
  {
    id: 'atraxa-superfriends',
    name: 'Atraxa, Praetors\' Voice',
    commander: 'Atraxa, Praetors\' Voice',
    colors: ['W', 'U', 'B', 'G'],
    cards: [
      'Atraxa, Praetors\' Voice',
      'Deepglow Skate',
      'Pir, Imaginative Rascal',
      'Toothy, Imaginary Friend',
      'Evolution Sage',
      'Flux Channeler',
      'Fathom Mage',
      'Vorel of the Hull Clade',
      'Inexorable Tide',
      'Doubling Season',
      'Parallel Lives',
      'Primal Vigor',
      'Oath of Nissa',
      'Oath of Teferi',
      'The Chain Veil',
      'Jace, the Mind Sculptor',
      'Teferi, Hero of Dominaria',
      'Narset, Parter of Veils',
      'Liliana, Dreadhorde General',
      'Elspeth, Sun\'s Champion',
      'Tamiyo, Field Researcher',
      'Vraska, Relic Seeker',
      'Ugin, the Spirit Dragon',
      'Nissa, Who Shakes the World',
      'Garruk, Cursed Huntsman',
      'Ashiok, Dream Render',
      'Karn Liberated',
      'Nicol Bolas, Dragon-God',
      'Teferi, Time Raveler',
      'Oko, Thief of Crowns',
      'Jace, Wielder of Mysteries',
      'Sorin, Grim Nemesis',
      'Ajani, Mentor of Heroes',
      'Swords to Plowshares',
      'Path to Exile',
      'Anguished Unmaking',
      'Assassin\'s Trophy',
      'Cyclonic Rift',
      'Wrath of God',
      'Damnation',
      'Supreme Verdict',
      'Sol Ring',
      'Arcane Signet',
      'Chromatic Lantern',
      'Coalition Relic',
      'Astral Cornucopia',
      'Everflowing Chalice',
      'Command Tower',
      'Breeding Pool',
      'Hallowed Fountain',
      'Watery Grave',
      'Godless Shrine',
      'Temple Garden',
      'Overgrown Tomb',
      'Flooded Strand',
      'Polluted Delta',
      'Windswept Heath',
      'Verdant Catacombs',
      'Misty Rainforest',
      'Yavimaya Coast',
      'Caves of Koilos',
      'Llanowar Wastes',
      'Adarkar Wastes',
      'Underground River',
      'Brushland',
      'Exotic Orchard',
      'Mana Confluence',
      'City of Brass',
      'Reflecting Pool',
      'Urborg, Tomb of Yawgmoth',
      'Forest',
      'Forest',
      'Forest',
      'Plains',
      'Plains',
      'Island',
      'Island',
      'Swamp',
      'Swamp',
      'Interplanar Beacon',
      'Karn\'s Bastion',
      'Tamiyo, the Moon Sage',
      'Nissa, Vital Force',
      'Vraska, Golgari Queen',
      'Kiora, Behemoth Beckoner',
      'Ajani Steadfast',
      'Sorin, Solemn Visitor',
      'Gideon Blackblade',
      'Vivien, Champion of the Wilds',
      'Tezzeret, Artifice Master',
      'Kasmina, Enigmatic Mentor',
      'Jiang Yanggu, Wildcrafter',
      'Spark Double',
      'Clever Impersonator',
      'Thrummingbird',
      'Grateful Apparition',
      'Contagion Engine',
      'Steady Progress',
      'Tezzeret\'s Gambit'
    ]
  },
  {
    id: 'prosper-treasure',
    name: 'Prosper, Tome-Bound',
    commander: 'Prosper, Tome-Bound',
    colors: ['B', 'R'],
    cards: [
      'Prosper, Tome-Bound',
      'Reckless Fireweaver',
      'Mayhem Devil',
      'Marionette Master',
      'Disciple of the Vault',
      'Nadier\'s Nightblade',
      'Academy Manufactor',
      'Xorn',
      'Professional Face-Breaker',
      'Goldspan Dragon',
      'Dockside Extortionist',
      'Magda, Brazen Outlaw',
      'Captain Lannery Storm',
      'Kalain, Reclusive Painter',
      'Rain of Riches',
      'Revel in Riches',
      'Mechanized Production',
      'Inspiring Statuary',
      'Pitiless Plunderer',
      'Black Market',
      'Phyrexian Arena',
      'Outpost Siege',
      'Theater of Horrors',
      'Chaos Wand',
      'Cunning Rhetoric',
      'Wild-Magic Sorcerer',
      'Commune with Lava',
      'Light Up the Stage',
      'Jeska\'s Will',
      'Ignite the Future',
      'Faithless Looting',
      'Feed the Swarm',
      'Deadly Dispute',
      'Village Rites',
      'Chaos Warp',
      'Rakdos Charm',
      'Bedevil',
      'Terminate',
      'Sol Ring',
      'Arcane Signet',
      'Rakdos Signet',
      'Talisman of Indulgence',
      'Mind Stone',
      'Thought Vessel',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Sensei\'s Divining Top',
      'Command Tower',
      'Blood Crypt',
      'Dragonskull Summit',
      'Sulfurous Springs',
      'Blackcleave Cliffs',
      'Blightstep Pathway',
      'Temple of Malice',
      'Rakdos Carnarium',
      'Tainted Peak',
      'Bojuka Bog',
      'Castle Locthwain',
      'Urborg, Tomb of Yawgmoth',
      'Cabal Coffers',
      'Treasure Vault',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Ragavan, Nimble Pilferer',
      'Laelia, the Blade Reforged',
      'Fevered Suspicion',
      'Share the Spoils',
      'Dream Devourer',
      'Etali, Primal Storm',
      'Stolen Strategy',
      'Possibility Storm',
      'Apex of Power',
      'Bituminous Blast',
      'Curse of Opulence',
      'Big Score',
      'Unexpected Windfall',
      'Strike It Rich',
      'Seize the Spoils',
      'Grim Hireling',
      'Ardent Elementalist',
      'You Find Some Prisoners',
      'Valakut Exploration',
      'Delayed Blast Fireball'
    ]
  },
  {
    id: 'lathril-elves',
    name: 'Lathril, Blade of the Elves',
    commander: 'Lathril, Blade of the Elves',
    colors: ['B', 'G'],
    cards: [
      'Lathril, Blade of the Elves',
      'Llanowar Elves',
      'Elvish Mystic',
      'Fyndhorn Elves',
      'Elves of Deep Shadow',
      'Deathrite Shaman',
      'Elvish Archdruid',
      'Priest of Titania',
      'Wirewood Channeler',
      'Marwyn, the Nurturer',
      'Circle of Dreams Druid',
      'Imperious Perfect',
      'Elvish Champion',
      'Dwynen, Gilt-Leaf Daen',
      'Elvish Clancaller',
      'Eladamri, Lord of Leaves',
      'Ezuri, Renegade Leader',
      'Joraga Warcaller',
      'Immaculate Magistrate',
      'Copperhorn Scout',
      'Quirion Ranger',
      'Scryb Ranger',
      'Timberwatch Elf',
      'Wellwisher',
      'Beast Whisperer',
      'Elvish Visionary',
      'Sylvan Messenger',
      'Realmwalker',
      'Vanquisher\'s Banner',
      'Herald\'s Horn',
      'Coat of Arms',
      'Door of Destinies',
      'Growing Rites of Itlimoc',
      'Kindred Summons',
      'Triumph of the Hordes',
      'Craterhoof Behemoth',
      'Finale of Devastation',
      'Natural Order',
      'Green Sun\'s Zenith',
      'Chord of Calling',
      'Assassin\'s Trophy',
      'Abrupt Decay',
      'Beast Within',
      'Heroic Intervention',
      'Sol Ring',
      'Arcane Signet',
      'Golgari Signet',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Skullclamp',
      'Command Tower',
      'Overgrown Tomb',
      'Woodland Cemetery',
      'Llanowar Wastes',
      'Blooming Marsh',
      'Darkbore Pathway',
      'Temple of Malady',
      'Golgari Rot Farm',
      'Tainted Wood',
      'Bojuka Bog',
      'Castle Garenbrig',
      'Nykthos, Shrine to Nyx',
      'Wirewood Lodge',
      'Gaea\'s Cradle',
      'Cavern of Souls',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Rhys the Redeemed',
      'Abomination of Llanowar',
      'Shaman of the Pack',
      'Poison-Tip Archer',
      'Prowess of the Fair',
      'Elderfang Venom',
      'Wolverine Riders',
      'Elvish Warmaster',
      'Tyvar Kell',
      'Gilt-Leaf Ambush',
      'Elvish Promenade',
      'Elven Ambush',
      'Eyeblight Massacre',
      'Miara, Thorn of the Glade',
      'Numa, Joraga Chieftain',
      'Nath of the Gilt-Leaf',
      'Nadier, Agent of the Duskenel',
      'Canopy Tactician',
      'Masked Admirers'
    ]
  },
  {
    id: 'ur-dragon-dragons',
    name: 'The Ur-Dragon',
    commander: 'The Ur-Dragon',
    colors: ['W', 'U', 'B', 'R', 'G'],
    cards: [
      'The Ur-Dragon',
      'Dragonlord Ojutai',
      'Dragonlord Silumgar',
      'Dragonlord Kolaghan',
      'Dragonlord Atarka',
      'Dragonlord Dromoka',
      'Scion of the Ur-Dragon',
      'Niv-Mizzet, Parun',
      'Niv-Mizzet, the Firemind',
      'Utvara Hellkite',
      'Scourge of Valkas',
      'Lathliss, Dragon Queen',
      'Bladewing the Risen',
      'Terror of the Peaks',
      'Ancient Copper Dragon',
      'Ancient Gold Dragon',
      'Ancient Silver Dragon',
      'Ancient Brass Dragon',
      'Ancient Bronze Dragon',
      'Old Gnawbone',
      'Savage Ventmaw',
      'Goldspan Dragon',
      'Glorybringer',
      'Thunderbreak Regent',
      'Scalelord Reckoner',
      'Dragon Tempest',
      'Temur Ascendancy',
      'Kindred Discovery',
      'Sarkhan Unbroken',
      'Sarkhan, Fireblood',
      'Sarkhan the Mad',
      'Patriarch\'s Bidding',
      'Living Death',
      'Crux of Fate',
      'Vanquisher\'s Banner',
      'Herald\'s Horn',
      'Urza\'s Incubator',
      'Dragon\'s Hoard',
      'Sol Ring',
      'Arcane Signet',
      'Chromatic Lantern',
      'Commander\'s Sphere',
      'Fist of Suns',
      'Morophon, the Boundless',
      'Command Tower',
      'Reflecting Pool',
      'Mana Confluence',
      'City of Brass',
      'Exotic Orchard',
      'Path of Ancestry',
      'Haven of the Spirit Dragon',
      'Crucible of the Spirit Dragon',
      'Unclaimed Territory',
      'Cavern of Souls',
      'Blood Crypt',
      'Breeding Pool',
      'Godless Shrine',
      'Hallowed Fountain',
      'Overgrown Tomb',
      'Sacred Foundry',
      'Steam Vents',
      'Stomping Ground',
      'Temple Garden',
      'Watery Grave',
      'Mountain',
      'Mountain',
      'Mountain',
      'Forest',
      'Forest',
      'Island',
      'Swamp',
      'Plains',
      'Scalelord Reckoner',
      'Drakuseth, Maw of Flames',
      'Balefire Dragon',
      'Hellkite Tyrant',
      'Hellkite Courser',
      'Backdraft Hellkite',
      'Steel Hellkite',
      'Wrathful Red Dragon',
      'Klauth, Unrivaled Ancient',
      'Tiamat',
      'Dragon Broodmother',
      'Karrthus, Tyrant of Jund',
      'Kolaghan, the Storm\'s Fury',
      'Ojutai, Soul of Winter',
      'Silumgar, the Drifting Death',
      'Atarka, World Render',
      'Dromoka, the Eternal',
      'Fearsome Awakening',
      'Spit Flame',
      'Earthquake',
      'Decimate',
      'Rishkar\'s Expertise',
      'Kindred Charge',
      'Kindred Summons',
      'Sarkhan\'s Triumph',
      'Tempt with Discovery',
      'Farseek',
      'Cultivate'
    ]
  },
  {
    id: 'aesi-sea-monsters',
    name: 'Aesi, Tyrant of Gyre Strait',
    commander: 'Aesi, Tyrant of Gyre Strait',
    colors: ['U', 'G'],
    cards: [
      'Aesi, Tyrant of Gyre Strait',
      'Tatyova, Benthic Druid',
      'Uro, Titan of Nature\'s Wrath',
      'Lotus Cobra',
      'Tireless Provisioner',
      'Risen Reef',
      'Coiling Oracle',
      'Sakura-Tribe Elder',
      'Wood Elves',
      'Farhaven Elf',
      'Solemn Simulacrum',
      'Scute Swarm',
      'Avenger of Zendikar',
      'Rampaging Baloths',
      'Roil Elemental',
      'Tatyova, Steward of Tides',
      'Koma, Cosmos Serpent',
      'Serpent of Yawning Depths',
      'Stormtide Leviathan',
      'Inkwell Leviathan',
      'Deep-Sea Kraken',
      'Slinn Voda, the Rising Deep',
      'Crush of Tentacles',
      'Whelming Wave',
      'Cyclonic Rift',
      'Simic Sky Swallower',
      'Nezahal, Primal Tide',
      'Spawning Kraken',
      'Pursuit of Knowledge',
      'Teferi\'s Ageless Insight',
      'Guardian Project',
      'Elemental Bond',
      'Burgeoning',
      'Exploration',
      'Kodama\'s Reach',
      'Cultivate',
      'Growth Spiral',
      'Three Visits',
      'Nature\'s Lore',
      'Skyshroud Claim',
      'Boundless Realms',
      'Sol Ring',
      'Arcane Signet',
      'Simic Signet',
      'Thought Vessel',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Command Tower',
      'Breeding Pool',
      'Hinterland Harbor',
      'Yavimaya Coast',
      'Botanical Sanctum',
      'Barkchannel Pathway',
      'Temple of Mystery',
      'Simic Growth Chamber',
      'Flooded Grove',
      'Alchemist\'s Refuge',
      'Reliquary Tower',
      'Mystic Sanctuary',
      'Castle Vantress',
      'Castle Garenbrig',
      'Boseiju, Who Shelters All',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Island',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Kiora, Behemoth Beckoner',
      'Kiora, the Crashing Wave',
      'Kiora Bests the Sea God',
      'Quest for Ula\'s Temple',
      'Serpent of the Endless Sea',
      'Vodalian Wave-Knight',
      'Gyruda, Doom of Depths',
      'Stormsurge Kraken',
      'Scourge of Fleets',
      'Tromokratis',
      'Lorthos, the Tidemaker',
      'Wrexial, the Risen Deep',
      'Ominous Seas',
      'Nadir Kraken',
      'Brinelin, the Moon Kraken',
      'Hullbreaker Horror',
      'Ruin Crab',
      'Rampant Growth',
      'Nissa, Steward of Elements',
      'Return of the Wildspeaker'
    ]
  },
  {
    id: 'isshin-attack-triggers',
    name: 'Isshin, Two Heavens as One',
    commander: 'Isshin, Two Heavens as One',
    colors: ['R', 'W', 'B'],
    cards: [
      'Isshin, Two Heavens as One',
      'Adeline, Resplendent Cathar',
      'Hero of Bladehold',
      'Hanweir Garrison',
      'Aurelia, the Warleader',
      'Combat Celebrant',
      'Karlach, Fury of Avernus',
      'Raiyuu, Storm\'s Edge',
      'Delina, Wild Mage',
      'Krenko, Tin Street Kingpin',
      'Commissar Severina Raine',
      'Professional Face-Breaker',
      'Captain Lannery Storm',
      'Brutal Hordechief',
      'Mardu Strike Leader',
      'Alesha, Who Smiles at Death',
      'Fervent Charge',
      'Reconnaissance',
      'Duelist\'s Heritage',
      'Gratuitous Violence',
      'True Conviction',
      'Berserkers\' Onslaught',
      'Shared Animosity',
      'Goblin War Drums',
      'Dictate of Erebos',
      'Grave Pact',
      'Phyrexian Arena',
      'Swords to Plowshares',
      'Path to Exile',
      'Anguished Unmaking',
      'Crackling Doom',
      'Mortify',
      'Chaos Warp',
      'Terminate',
      'Wrath of God',
      'Damn',
      'Blasphemous Act',
      'Sol Ring',
      'Arcane Signet',
      'Boros Signet',
      'Orzhov Signet',
      'Rakdos Signet',
      'Talisman of Conviction',
      'Talisman of Hierarchy',
      'Talisman of Indulgence',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Command Tower',
      'Blood Crypt',
      'Godless Shrine',
      'Sacred Foundry',
      'Dragonskull Summit',
      'Isolated Chapel',
      'Clifftop Retreat',
      'Caves of Koilos',
      'Battlefield Forge',
      'Sulfurous Springs',
      'Savai Triome',
      'Nomad Outpost',
      'Path of Ancestry',
      'Vault of Champions',
      'Spectator Seating',
      'Luxury Suite',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Swamp',
      'Swamp',
      'Swamp',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Aurelia\'s Fury',
      'Agitator Ant',
      'Karazikar, the Eye Tyrant',
      'Adriana, Captain of the Guard',
      'Hellrider',
      'Breena, the Demagogue',
      'Akroma, Vision of Ixidor',
      'Emberwilde Captain',
      'Goldnight Commander',
      'Frontline Medic',
      'Reconnaissance Mission',
      'Tectonic Giant',
      'Wulfgar of Icewind Dale',
      'Port Razer',
      'Moraug, Fury of Akoum',
      'Anger',
      'Legion Loyalist',
      'Archon of Cruelty',
      'Curse of Opulence',
      'Curse of Disturbance',
      'Mirror Entity',
      'Dolmen Gate',
      'Iroas, God of Victory',
      'Cathars\' Crusade',
      'Fiery Emancipation',
      'Mardu Ascendancy'
    ]
  },
  {
    id: 'miirym-dragon-tokens',
    name: 'Miirym, Sentinel Wyrm',
    commander: 'Miirym, Sentinel Wyrm',
    colors: ['U', 'R', 'G'],
    cards: [
      'Miirym, Sentinel Wyrm',
      'Thrakkus the Butcher',
      'Ganax, Astral Hunter',
      'Astral Dragon',
      'Ancient Copper Dragon',
      'Ancient Silver Dragon',
      'Ancient Bronze Dragon',
      'Old Gnawbone',
      'Savage Ventmaw',
      'Goldspan Dragon',
      'Utvara Hellkite',
      'Scourge of Valkas',
      'Terror of the Peaks',
      'Dragon Broodmother',
      'Lathliss, Dragon Queen',
      'Dragonmaster Outcast',
      'Thunderbreak Regent',
      'Glorybringer',
      'Skyline Despot',
      'Demanding Dragon',
      'Balefire Dragon',
      'Drakuseth, Maw of Flames',
      'Inferno of the Star Mounts',
      'Klauth, Unrivaled Ancient',
      'Rishkar\'s Expertise',
      'Kindred Summons',
      'Doubling Season',
      'Parallel Lives',
      'Primal Vigor',
      'Dragon Tempest',
      'Temur Ascendancy',
      'Garruk\'s Uprising',
      'Elemental Bond',
      'Guardian Project',
      'Temur Charm',
      'Beast Within',
      'Chaos Warp',
      'Cyclonic Rift',
      'Nature\'s Claim',
      'Krosan Grip',
      'Sol Ring',
      'Arcane Signet',
      'Gruul Signet',
      'Simic Signet',
      'Izzet Signet',
      'Chromatic Lantern',
      'Dragon\'s Hoard',
      'Urza\'s Incubator',
      'Herald\'s Horn',
      'Command Tower',
      'Breeding Pool',
      'Stomping Ground',
      'Steam Vents',
      'Ketria Triome',
      'Frontier Bivouac',
      'Hinterland Harbor',
      'Rootbound Crag',
      'Sulfur Falls',
      'Yavimaya Coast',
      'Shivan Reef',
      'Karplusan Forest',
      'Exotic Orchard',
      'Path of Ancestry',
      'Haven of the Spirit Dragon',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Forest',
      'Island',
      'Island',
      'Island',
      'Island',
      'Sarkhan, Fireblood',
      'Sarkhan Unbroken',
      'Spark Double',
      'Sakashima of a Thousand Faces',
      'Bramble Sovereign',
      'Flameshadow Conjuring',
      'Molten Echoes',
      'Kindred Charge',
      'Cursed Mirror',
      'Reflections of Littjara',
      'Irenicus\'s Vile Duplication',
      'Fable of the Mirror-Breaker',
      'Clone',
      'Phantasmal Image',
      'Sakashima the Impostor',
      'Temur Sabertooth',
      'Monster Manual',
      'Greater Good',
      'Return of the Wildspeaker',
      'Rhythm of the Wild',
      'Hull Breach',
      'Decimate'
    ]
  },
  {
    id: 'najeela-warriors',
    name: 'Najeela, the Blade-Blossom',
    commander: 'Najeela, the Blade-Blossom',
    colors: ['W', 'U', 'B', 'R', 'G'],
    cards: [
      'Najeela, the Blade-Blossom',
      'Mindblade Render',
      'Tymna the Weaver',
      'Edric, Spymaster of Trest',
      'Blood-Chin Fanatic',
      'Bloodsoaked Champion',
      'Bramblewood Paragon',
      'Blood-Chin Rager',
      'Brighthearth Banneret',
      'Champion of Lambholt',
      'Chief of the Edge',
      'Chief of the Scale',
      'Civic Saber',
      'Combat Celebrant',
      'Devoted Crop-Mate',
      'Druid of the Anima',
      'Embercleave',
      'Etherium Sculptor',
      'Ezuri, Claw of Progress',
      'Goblin Bushwhacker',
      'Grand Warlord Radha',
      'Gruul Spellbreaker',
      'Herald of Secret Streams',
      'Jazal Goldmane',
      'Kargan Intimidator',
      'Khenra Charioteer',
      'Lovisa Coldeyes',
      'Mardu Woe-Reaper',
      'Mindblade Render',
      'Mirror Entity',
      'Najeela, the Blade-Blossom',
      'Nature\'s Will',
      'Neheb, the Eternal',
      'Oakhame Adversary',
      'Ogre Battledriver',
      'Raiders\' Spoils',
      'Reckless Bushwhacker',
      'Rushblade Commander',
      'Samut, Voice of Dissent',
      'Secure the Wastes',
      'Shared Animosity',
      'Signal Pest',
      'Soul-Scar Mage',
      'Thrasher Brute',
      'Throne of the God-Pharaoh',
      'Vault of the Archangel',
      'Vizier of Remedies',
      'War-Name Aspirant',
      'Warrior\'s Oath',
      'Windswift Slice',
      'Zurgo Helmsmasher',
      'Derevi, Empyrial Tactician',
      'Druids\' Repository',
      'Bear Umbra',
      'Sword of Feast and Famine',
      'Aggravated Assault',
      'Savage Beating',
      'Aurelia, the Warleader',
      'Hellkite Charger',
      'Swords to Plowshares',
      'Path to Exile',
      'Cyclonic Rift',
      'Heroic Intervention',
      'Assassin\'s Trophy',
      'Anguished Unmaking',
      'Kindred Discovery',
      'Reconnaissance',
      'Dolmen Gate',
      'Sol Ring',
      'Arcane Signet',
      'Chromatic Lantern',
      'Commander\'s Sphere',
      'Fellwar Stone',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Command Tower',
      'Mana Confluence',
      'City of Brass',
      'Exotic Orchard',
      'Reflecting Pool',
      'Cavern of Souls',
      'Unclaimed Territory',
      'Path of Ancestry',
      'Blood Crypt',
      'Breeding Pool',
      'Godless Shrine',
      'Hallowed Fountain',
      'Overgrown Tomb',
      'Sacred Foundry',
      'Steam Vents',
      'Stomping Ground',
      'Temple Garden',
      'Watery Grave',
      'Forest',
      'Island',
      'Mountain',
      'Plains',
      'Swamp',
      'Bloodstained Mire',
      'Flooded Strand',
      'Polluted Delta',
      'Windswept Heath',
      'Wooded Foothills'
    ]
  },
  {
    id: 'dihada-legends',
    name: 'Dihada, Binder of Wills',
    commander: 'Dihada, Binder of Wills',
    colors: ['R', 'W', 'B'],
    cards: [
      'Dihada, Binder of Wills',
      'Shanid, Sleepers\' Scourge',
      'Arvad the Cursed',
      'Kethis, the Hidden Hand',
      'Captain Sisay',
      'Jhoira, Weatherlight Captain',
      'Ratadrabik of Urborg',
      'Elenda, the Dusk Rose',
      'Teysa Karlov',
      'Aurelia, the Warleader',
      'Adriana, Captain of the Guard',
      'Alesha, Who Smiles at Death',
      'Anafenza, the Foremost',
      'Gisela, Blade of Goldnight',
      'Liesa, Forgotten Archangel',
      'Kambal, Consul of Allocation',
      'Odric, Lunarch Marshal',
      'Thalia, Guardian of Thraben',
      'Thalia, Heretic Cathar',
      'Tajic, Legion\'s Edge',
      'Krenko, Tin Street Kingpin',
      'Kaya, Geist Hunter',
      'Sorin, Grim Nemesis',
      'Elspeth, Sun\'s Champion',
      'Blackblade Reforged',
      'Helm of the Host',
      'Heroes\' Podium',
      'Relic of Legends',
      'Honor-Worn Shaku',
      'Day of Destiny',
      'Urza\'s Ruinous Blast',
      'Primevals\' Glorious Rebirth',
      'Kamahl\'s Druidic Vow',
      'Swords to Plowshares',
      'Path to Exile',
      'Anguished Unmaking',
      'Crackling Doom',
      'Damn',
      'Wrath of God',
      'Sol Ring',
      'Arcane Signet',
      'Boros Signet',
      'Orzhov Signet',
      'Rakdos Signet',
      'Commander\'s Sphere',
      'Lightning Greaves',
      'Swiftfoot Boots',
      'Command Tower',
      'Blood Crypt',
      'Godless Shrine',
      'Sacred Foundry',
      'Dragonskull Summit',
      'Isolated Chapel',
      'Clifftop Retreat',
      'Plaza of Heroes',
      'Eiganjo, Seat of the Empire',
      'Shizo, Death\'s Storehouse',
      'Savai Triome',
      'Nomad Outpost',
      'Vault of Champions',
      'Spectator Seating',
      'Luxury Suite',
      'Path of Ancestry',
      'Phyrexian Tower',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Plains',
      'Swamp',
      'Swamp',
      'Swamp',
      'Swamp',
      'Mountain',
      'Mountain',
      'Mountain',
      'Mountain',
      'Verrak, Warped Sengir',
      'Loran of the Third Path',
      'Feldon of the Third Path',
      'Teshar, Ancestor\'s Apostle',
      'Vona, Butcher of Magan',
      'Kaervek the Merciless',
      'Queen Marchesa',
      'Zurgo Helmsmasher',
      'Gerrard, Weatherlight Hero',
      'Hero\'s Blade',
      'Bloodforged Battle-Axe',
      'Search for Glory',
      'Time of Need',
      'Yomiji, Who Bars the Way',
      'Board the Weatherlight',
      'Weatherlight',
      'Kaya\'s Ghostform',
      'Gift of Immortality',
      'Nettlecyst',
      'Bontu\'s Monument',
      'Hazoret\'s Monument',
      'Oketra\'s Monument',
      'Boros Charm',
      'Utter End'
    ]
  }
];

/**
 * Get a precon deck by ID
 */
export function getPreconById(id) {
  return PRECON_DECKS.find(deck => deck.id === id) || null;
}

/**
 * Get all precon decks (for populating dropdown)
 */
export function getAllPrecons() {
  return PRECON_DECKS.map(({ id, name, commander, colors, cards }) => ({
    id,
    name,
    commander,
    colors,
    cardCount: cards.length
  }));
}
